  production:
    DEVISE_SECRET_KEY: "43be4805bb1f822d22f8d2fb74a756e9ac235ffe532af4a4d4188f8f5657449bb519a1e844da730e4fb70832146d5587c823524d8036b49bf190762c04513f97"
    SENDGRID_PASS: "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"
    FACEBOOK_APP_ID: "427164184532014"
    FACEBOOK_APP_SECRET: "b36eba98497efb0b16705054e0020c9b"
    GOOGLE_APP_ID: "253468016081-e90u1g83eir6i5tjt8cvuaa83bjskvql.apps.googleusercontent.com"
    GOOGLE_APP_SECRET: "7Uymd7CPz3DUo_-9f2Oras3O"
    GOOGLE_API_KEY: "AIzaSyB1YVqZDu7QflsYUp1-nTyxvLgbdoYi9JM"
    DATABASE_URL: "postgres://mfftserbjdrolj:879b804877a7438ee56f1851107bc455daab8a46fec4d6a2f2a6a78c0a137827@ec2-50-17-225-140.compute-1.amazonaws.com:5432/d8sghg3r812bhn"
